### ISSUE TITLE
Error: non-zero exit status 1

### ISSUE THREAD

**Issue by ShalokShalom** [seadanda/protonvpn-applet#11]
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-applet", line 118, in run
    result = subprocess.check_output(VPNCommand.status.value.split()).decode(sys.stdout.encoding)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'protonvpn', 's']' returned non-zero exit status 1.
```

KaOS Linux. KDE Plasma 5, current. How can I help?

**Comment by seadanda** [comment]
Hi, 

This error is just indicative of a problem with the protonvpn linux-cli, which is used as a backend here. Have you installed, configured and initialised your profile in protonvpn correctly?
You could test this by running `protonvpn -v` to check the version you have installed (if it's installed) and then `sudo protonvpn c -f` should complain if you haven't run `sudo protonvpn init` yet.

In the mean time I have simplified how the status is checked, since the upstream is written in python now (and has been for a while but I've been too busy in work to change it).

I'm merging in some pkexec functionality and cleaning up the code, then I'll make a release.

Let me know how it goes.

**Comment by ShalokShalom** [comment]
Hi

I get a new error, idk if its related to the previous one:
```

 [root@cosmos64 shalokshalom]# protonvpn-applet 
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
kf.notifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
```

Is the authentification different than that from my Protonmail account? 
Since I used that one to login into the Android version of ProtonVPN and that works perfect. 

Nice day :D

**Comment by seadanda** [comment]
Hi,

It looks like you're trying to run the application as root, which isn't intended. That is what the QStandardPaths error is referring to - 1000 is your user, 0 is root. Try running `protonvpn-applet` as a regular user.
The kf.notifications one could also be related to running a graphical application which tries to use the notification daemon as root, but the KDE session is started as your normal user. I can't be sure since I don't use KDE, but I think this will also be fixed by running as a regular user.

**Comment by ShalokShalom** [comment]
It asks me to run it as root and fails, if I dont do so.

**Comment by seadanda** [comment]
What version of protonvpn-applet are you using? And what version of protonvpn linux-cli are you using? Please reply with the output of `protonvpn -v`

**Comment by ShalokShalom** [comment]
ProtonVPN-CLI v2.2.4

**Comment by ShalokShalom** [comment]
~~0.1.5~~ 0.1.7 from your app

**Comment by seadanda** [comment]
Well those are versions which work together, it is actually the protonvpn linux-cli which tells you to run as root, but `protonvpn-applet` uses sudo behind the scenes to run `protonvpn` commands. Have you got sudo installed and configured for your user? could you try running protonvpn-applet as a normal user and pasting your output here? Thanks.

**Comment by ShalokShalom** [comment]
It seems it is unhappy with my credentials now. 
Did you read my question regarding the password?
Is it supposed to be my normal Protonmail password, as in the Android version of ProtonVPN?

**Comment by seadanda** [comment]
It sounds like your protonvpn config is in some way broken. Try logging in as your normal user, then run `sudo protonvpn init` and following the steps there.

For your username and password, that depends on how you have it set up. You can find your VPN username and password if you log in to your Protonmail account and going to settings -> ProtonVPN and it will show your username and password as configured for ProtonVPN. There are further instructions [here](https://protonvpn.com/support/vpn-login/)

**Comment by seadanda** [comment]
Hi @ShalokShalom did you manage to fix your protonvpn credentials in the end? I'll close this unless you have an issue with protonvpn-applet that I can help you with.
