### ISSUE TITLE
Call the CLI without relying on passwordless sudo

### ISSUE THREAD

**Issue by seadanda** [seadanda/protonvpn-applet#3]
Using passwordless sudo calls within the program is an inelegant solution, but running as root is overkill. Find a way to run the applet under the current user while still satisfying the requirement that the cli is run with root privileges. 

Maybe look into using a systemd service like the NetworkManager service and applet interact. Run/enable the service as root and interact with it using a user tool. I'll need to do some reading on this, advice welcome.

Another option is a popup box to enter sudo password for (dis)connections, although this would be annoying.

**Comment by VainlyStrain** [comment]
Hi!

First thanks for the work you put into this. I really needed a protonvpn UI/tray app.

I guess the problem with passworded sudo is that no terminal is open to enter it? I've got a workaround! Use polkit instead of sudo. It gives a graphical password prompt.

(replace in all commands sudo with pkexec)

However, you may run into a not-initialized error from protonvpn-cli. This can be fixed by initializing protonvpn again, but with pkexec insteasd of sudo. Also, as a hypothesis, you could copy the config into polkit user & address permissions. Haven't tried that though.

Hope I could help :)

**Comment by seadanda** [comment]
Hi! 

Thanks for the heads up, this is great. I've never messed around with polkit before, and I don't use a DE so I was blissfully unaware of the advantages. I've implemented and tested and it works as expected, although as you pointed out you do need to re-initialise protonvpn.

Ideally, the applet would just run on top of protonvpn-cli-ng with no extra config needed. It seems that the way polkit and sudo escalate privileges differs in a few ways, with pkexec being a lot more restrictive. I wonder if there's any way to get around that.

I'm not really sure what you mean by 
> copy the config into polkit user & address permissions

Which config?

**Comment by ShalokShalom** [comment]
Hi!

I am a noob and I don't know quite how, while in our distro does KWallet need no password and it does not prompt for one either. I did read the docs and I imagine it is using this one: https://github.com/KDE/kwallet-pam Maybe that can help.

**Comment by seadanda** [comment]
Hi,
Thanks for the suggestion. This issue was actually fixed in the `pkexec` branch in January, but I never merged it into master. I'm just merging now but letting people have the choice
