### ISSUE TITLE
ip link parse exception

### ISSUE THREAD

**Issue by echogram** [seadanda/protonvpn-applet#7]
Applet worked fine on linux 5.4.17 but now receive the following exception on 5.4.18-1-MANJARO

[xxx ~]$ protonvpn-applet 
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
Traceback (most recent call last):
  File "/usr/bin/protonvpn-applet", line 62, in run
    raise VPNStatusException('Cannot parse `ip link` output.')
__main__.VPNStatusException: Cannot parse `ip link` output.
Aborted (core dumped)

[xxx]$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp10s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: wlp8s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
5: proton0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
(mac addresses xx-ed out)

[xxx]$ protonvpn status
Status:       Connected
Time:         0:00:07
IP:           95.168.185.239
Server:       UK#14
Features:     Normal
Protocol:     UDP
Kill Switch:  Disabled
Country:      United Kingdom
City:         London
Load:         30%
Received:     17.07 KB
Sent:         5.25 KB

**Comment by seadanda** [comment]
Hi echogram,

Thanks for the bug report! Looks like the protonvpn team have changed the name of the network device they create.
In the past, checking the status with protonvpn status took a verrry long time, whereas checking ip link for the tun device was very fast, so I went for that instead (since that's what the old cli tool did anyway) but now with the python tool it is much faster, so I will change the applet to rely on protonvpn-cli-ng's status call once again, to make the applet immune to changes like this in the future.
I'll fix this and make a release, shouldn't take long.

Cheers

Edit: clarify why I'm changing the status behaviour

**Comment by seadanda** [comment]
Fixed in master. Tested working, let me know if you have any problems.

**Comment by echogram** [comment]
@seadanda,

Great - thanks for the quick response.

Any chance you could update the AUR package so I can update my machine using that?

Thanks again
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


17 Feb 2020, 15:05 by notifications@github.com:

**Comment by seadanda** [comment]
@echogram done.

**Comment by echogram** [comment]
@seadanda many thanks - seems to be working fine with ProtonVPN-CLI v2.2.2 under Linux 5.5.2

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


18 Feb 2020, 09:52 by notifications@github.com:
